site:
  title: Lookyloo
  url: https://lookyloo.github.io/docs/
  start_page: docs::index
content:
  sources:
    - url:  https://lookyloo.github.io/docs/
      branches: 
    
ui:
  bundle:
    url:  https://lookyloo.github.io/docs/blob/master/ui-bundle.zip?raw=true
    snapshot: true